### ISSUE TITLE
Allow input of your Coordinates into the map

### ISSUE THREAD

**Issue by badbud65** [canonn-science/CanonnED3D-Map#14]
Allow input of your Coordinates into the map this would then allow you to see POI's that are nearby that you may want to visit. 

## Expected Behavior
Insert your current Coordinates in XYZ or System Name Format and then the map will centre on that possition

## Current Behavior
Currently it doesn't do this as far as I'm aware

## Possible Solution
Input field for Coordinates or System Name. The latter would require that the system is current know by EDSM so using EDSM should be a prerequisite

## Steps to Reproduce (for bugs)
N/A

## Context
I currently use several spreadsheets to locate nearby POI's

## Your Environment
N/A

**Comment by derrickmehaffy** [comment]
@badbud65 sorry for the late reply, currently this isn't possible with this version of the map, we are rewriting it to be far more accommodating to features like this but the upstream base code we are working with is https://github.com/gbiobob/ED3D-Galaxy-Map created by BioBob

**Comment by derrickmehaffy** [comment]
I'm going to close this issue for now, we can revisit it once our rewrite is finished.
