### ISSUE TITLE
Incorrect canvas height value

### ISSUE THREAD

**Issue by kam1sh** [canonn-science/CanonnED3D-Map#22]
Hi! I'm working on integrating your map sources (with copyrights, of course!) into one web site, and right now I'm facing some problems with map `<canvas>` element. 
If you help us, I'm sure we could donate something to Canonn...

## Expected Behavior

Map should take up all space available.

## Current Behavior

Map canvas has incorrect height value:

```html
<canvas width="1918" height="0" style="width: 1918px; height: 0px; z-index: 5;"></canvas>
```

As a result, map has incorrect position and size on page:

![image](https://user-images.githubusercontent.com/14600211/87245931-51fb2f80-c452-11ea-839d-b98a6fb06147.png)

## Possible Solution

_???_

## Steps to Reproduce (for bugs)

I have an example repository that illustrates issue: https://github.com/kam1sh/kvision-sandbox/tree/ed3dmap/src/main/resources

(Before it was writte in KVision (Kotlin/JS web framework), but I managed to get it working only on plain HTML/JS/CSS)

## Context

I want to have Elite Dangerous 3D map with our waypoints (fleet carriers, thargoids NHSS, faction objectives etc) on our web site.

## Your Environment

* Browser Name and version: Vivaldi 3.1.1929.45 (Stable channel) (64-bit) (Chrome/83.0.4103.119)
* Operating System and version (desktop or mobile): Linux (openSUSE Leap 15), desktop/laptop

Thank you.
Igor

**Comment by derrickmehaffy** [comment]
Hi @kam1sh we didn't build ED3D and are only using it to run the maps. You will want to check with https://github.com/gbiobob/ED3D-Galaxy-Map

**Comment by derrickmehaffy** [comment]
The CSS we use to define with map container is here: https://github.com/canonn-science/CanonnED3D-Map/blob/ad57146a24981df00a6cd45a93ecbaa01727d309/Source/index.html#L35-L42

**Comment by kam1sh** [comment]
@derrickmehaffy Hey, it works! Thank you for pointers with CSS and for fast response =)
